resource_group_name          = "ContosoProdRG"
aks_cluster_name             = "ContosoProdAks"
log_analytics_workspace_name = "ContosoProdAksWorkspace"
domain_name_label            = "contosoprodtestvm"
firewall_name                = "ContosoProdFirewall"
acr_name                     = "ContosoProdAcr"
bastion_host_name            = "ContosoProdBastionHost"
key_vault_name               = "ContosoProdAksKeyVault"